
module Credentials

	GENERIC_USERNAME = 'test_user2'
	GENERIC_PASSWORD = 'test_user2'
	GENERIC_FIRST_NAME = 'test_user2'
	GENERIC_INSTITUTION_NAME = 'Test Institution'
	GENERIC_INSTITUTION_ID = '1'
	GENERIC_INSTITUTION_CHILD_NAME = 'Test sub-inst01'
	GENERIC_INSTITUTION_CHILD_ID = '30'

	
end