
module Credentials

	GENERIC_USERNAME = 'test_user2'
	GENERIC_PASSWORD = 'test_user2'
	GENERIC_FIRST_NAME = 'test_user2'
	GENERIC_INSTITUTION_NAME = 'Test Institution'
	GENERIC_INSTITUTION_ID = '1'
	GENERIC_INSTITUTION_CHILD_NAME = 'Test sub-inst01'
	GENERIC_INSTITUTION_CHILD_ID = '30'

	REQ_EDITOR_USERNAME = 'require123'
	REQ_EDITOR_PASSWORD = 'require123'
	REQ_EDITOR_FIRST_NAME = 'Require123'
	REQ_EDITOR_INSTITUTION_NAME = 'Smithsonian Institution'
	REQ_EDITOR_INSTITUTION_ID = '6'
	REQ_EDITOR_INSTITUTION_CHILD_NAME = 'Museum of Natural History'
	REQ_EDITOR_INSTITUTION_CHILD_ID = '35'

end