development:
  rss:                    http://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [pwillet.ucop.edu, mstrong@ucop.edu, sfisher@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   UA-30638119-8
  google_analytics_host:  cdlib.org

development_nonlocal:
  development

stage:
  rss:                    http://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   UA-30638119-9
  google_analytics_host:  cdlib.org

stage_development:
  stage

production:
  rss:                    http://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   ""
  google_analytics_host:  ""

production_development:
  production


test:
  rss:                    http://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [pwillet.ucop.edu, mstrong@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   ""
  google_analytics_host:  ""

test_nonlocal:
  development