development:
  rss:                    https://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [pwillet.ucop.edu, mstrong@ucop.edu, sfisher@ucop.edu, briley@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   UA-30638119-8
  google_analytics_host:  cdlib.org
  host_for_email_links:   https://dmp2-dev.cdlib.org
  ld_path_for_pandoc:     /dmp2/local/lib64
  pdf_font:
    bold: Crimson-Bold.ttf
    italic: Crimson-Italic.ttf
    bold_italic: Crimson-BoldItalic.ttf
    normal: Crimson-Roman.ttf
  mailer_submission_default:
    subject: '[DMPTool] (development) Your plan has been submitted for feedback'
    body: 'Hello [User Name], your DMP "[Plan Name]" has been submitted for feedback from an administrator at your institution.  If you have questions pertaining to this action, please contact us at http://cdlib-stage.cdlib.org/services/uc3/contact.html'
  contact_us_url: 'http://cdlib-stage.cdlib.org/services/uc3/contact.html'

development_nonlocal:
  development

stage:
  rss:                    https://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   UA-30638119-9
  google_analytics_host:  cdlib.org
  host_for_email_links:   https://dmp2-stg.cdlib.org
  ld_path_for_pandoc:     /dmp2/local/lib64
  pdf_font:
    bold: Crimson-Bold.ttf
    italic: Crimson-Italic.ttf
    bold_italic: Crimson-BoldItalic.ttf
    normal: Crimson-Roman.ttf
  mailer_submission_default:
    subject: '[DMPTool] (staging) Your plan has been submitted for feedback'
    body: 'Hello [User Name], your DMP "[Plan Name]" has been submitted for feedback from an administrator at your institution.  If you have questions pertaining to this action, please contact us at http://cdlib-stage.cdlib.org/services/uc3/contact.html'
  contact_us_url: 'http://cdlib-stage.cdlib.org/services/uc3/contact.html'

stage_development:
  stage

production:
  rss:                    https://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [uc3@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   UA-30638119-10
  google_analytics_host:  dmptool.org
  host_for_email_links:   https://dmptool.org
  ld_path_for_pandoc:     /dmp2/local/lib64
  pdf_font:
    bold: Crimson-Bold.ttf
    italic: Crimson-Italic.ttf
    bold_italic: Crimson-BoldItalic.ttf
    normal: Crimson-Roman.ttf
  mailer_submission_default:
    subject: '[DMPTool] Your plan has been submitted for feedback'
    body: 'Hello [User Name], your DMP "[Plan Name]" has been submitted for feedback from an administrator at your institution.  If you have questions pertaining to this action, please contact us at http://www.cdlib.org/services/uc3/contact.html'
  contact_us_url: 'http://www.cdlib.org/services/uc3/contact.html'

production_development:
  production


test:
  rss:                    https://blog.dmptool.org/feed
  blog:                   http://blog.dmptool.org
  feedback_email_to:      [pwillet.ucop.edu, mstrong@ucop.edu]
  feedback_email_from:    no-reply-dmptool@ucop.edu
  recaptcha_public_key:   6Ld2AAYAAAAAAKrPZimDhCZY56x_VK2RuAgao1_6
  recaptcha_private_key:  6Ld2AAYAAAAAAHAzVcdFizHHGPInfgr4aGOm4n4x
  google_analytics_key:   ""
  google_analytics_host:  ""
  contact_us_url: 'http://cdlib-stage.cdlib.org/services/uc3/contact.html'

test_nonlocal:
  development